monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: info
        handler: split
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        channels: [ "!event", "!deprecation", "!doctrine" ]
      split:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        max_files: 30
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: info
        handler: split
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        channels: [ "!event", "!deprecation", "!doctrine", '!http_client', '!request' ]
      split:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: info
        max_files: 30
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]