# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# Redirect root to default locale
app_root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: false

# API controllers (no locale prefix)
api:
    resource:
        path: ../src/Api/Controller/
        namespace: App\Api\Controller
    type: attribute

# Web controllers (with locale prefix)
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: en
